### ISSUE TITLE
script ToDo list

### ISSUE THREAD

**Issue by meleu** [UDb23/rpie-ovl#14]
- [x] put arcade overlay files in `arcade/` folder. [done in #13]
- [x] add an updating feature to the script. [done in #15]
- [ ] add support for clones (multiple .zip.cfg files for same game)
- [ ] make script able to install overlays for other systems (not only arcade).
- [ ] clean the script (the code is a bit ugly and messy)
- [x] add info.txt for all roms to enable new script.
- [ ] complete clones data in info.txt for all roms

**Comment by UDb23** [comment]
added new items to todo list

**Comment by meleu** [comment]
I've put the new script's TODO list here: https://github.com/meleu/rpie-art/issues/1
You can make new suggestion there. ;-)

**Comment by meleu** [comment]
Let's avoid duplication. The script ToDo is at its own repository. Closing this one. :-)

**Comment by UDb23** [comment]
sure, right.
