### ISSUE TITLE
ToDo list for Artwork

### ISSUE THREAD

**Issue by UDb23** [UDb23/rpie-ovl#34]
- [ ] Create and add missing launch and "scrape" images
- [x] The End: overlay creation from cabinet pictures
- [x] Silkworm overlay creation
- [x] Silkworm lauching and scrape 
- [x] Atari Sky diver (mame 2003 plus + backdrop)
- [ ] FInalize correct Psikyo logo 
- [x] Snes Overlays
- [ ] Mame Generic Arcade
- [x] Spiders ovl + fix mame 2010 aspect ratio
- [ ] Mega Man NES w bosses (@meleu)
- [x] DoDonPachi Dai-Ou-Jou (FBA)
- [x] Blazing Star
- [x] Pulstar
- [x] Rampage
- [ ] Tengai (bars)
- [ ] Gunbird 1
- [ ] Gunbird 2 (english texts)
- [x] Macross II
- [x] Aero Fighters 2
- [ ] Blood Bros
- [ ] Flicky
- [x] Shock Troopers: 2nd Squad
- [ ] Sexy Parodius
- [ ] Wonderboy
- [x] Zaxxon 
- [ ] Rastan
- [ ] Mr. Do
- [x] Congo Bongo
- [ ] Lady Bug
- [x] P-47
- [ ] Cheeky mouse
- [ ] Alien Syndrome
- [ ] Caveman Ninja marquee
- [ ] Cosmic Guerilla marquee
- [x] Magical Spot sideart
- [ ] The End full original bezel
- [ ] Outzone
- [x] Viper Phase 1 (req)
- [ ] Zaccaria "Stars" bezel
- [ ] Zaccaria Vanguard bezel
- [ ] Crazy Balloon
- [ ] Battle Bakraid (req)
- [ ] Klax
- [ ] Battle Garegga (req)
- [ ] Nibbler marquee & bezel
- [x] Missile command
- [x] Strato Fighter

**Comment by meleu** [comment]
- [x] Silkworm lauching and scrape

**Comment by UDb23** [comment]
the end done

**Comment by UDb23** [comment]
Aero Fighters 2 done!

**Comment by Wilstorm** [comment]
Hey UDb, I was wondering if it's ok to make a request here for overlays or is better to do so on the RetroPie forum? I was thinking about 4 or 5 old classics. Definitely no hurry if at all as I know you do this in your spare time but I thought I would ask and see if they could be tacked on a list if possible.

**Comment by UDb23** [comment]
On top of the overlays you see in the list here I have multiple other overlays in the works, at various stages of progress. What games are you interested in ?

**Comment by Wilstorm** [comment]
They are a few older ones as you have covered most of the main ones I play (thank you!) but figured maybe a few more could be added to the list. If it doesn't fit into you plans or schedule that's ok too! Thanks UDb!

1. Zaxxon [(Zaxxon Google artwork)](https://www.google.com/search?biw=1322&bih=789&tbm=isch&sa=1&ei=D2gcWp7HOsPcwQKIp6yoDA&q=rastan+arcade+cabinet&oq=rastan+arcade+cabinet&gs_l=psy-ab.3..0i24k1.39966.41404.0.41691.6.6.0.0.0.0.233.1123.2-5.5.0....0...1c.1.64.psy-ab..1.4.887...0i7i30k1j0i7i5i30k1.0.YgTirbGSN8Y)
2. Rastan [(Rastan Google artwork)](https://www.google.com/search?biw=1322&bih=789&tbm=isch&sa=1&ei=D2gcWp7HOsPcwQKIp6yoDA&q=rastan+arcade+cabinet&oq=rastan+arcade+cabinet&gs_l=psy-ab.3..0i24k1.39966.41404.0.41691.6.6.0.0.0.0.233.1123.2-5.5.0....0...1c.1.64.psy-ab..1.4.887...0i7i30k1j0i7i5i30k1.0.YgTirbGSN8Y)
3. Mr. Do [(Mr. Do Google Artwork)](https://www.google.com/search?biw=1322&bih=789&tbm=isch&sa=1&ei=22ccWrTDJ4XewQLymrfQCg&q=mr.+do+arcade+cabinet&oq=mr.+do+arcade+cabinet&gs_l=psy-ab.3...49498.50761.0.51351.6.6.0.0.0.0.312.539.2-1j1.2.0....0...1c.1.64.psy-ab..4.0.0....0.Nb1ZmoTlZC4#imgrc=Kcz9a3S-fAvdEM:)
4. Congo Bongo [(Congo Bongo Google artwork)](https://www.google.com/search?biw=1322&bih=789&tbm=isch&sa=1&ei=oWccWpTVIYLfwAK9saeYAw&q=congo+bongo+arcade+cabinet&oq=congo+bongo+arcade+cabinet&gs_l=psy-ab.3...54129.57004.0.57411.13.12.0.0.0.0.349.1786.2-5j2.7.0....0...1c.1.64.psy-ab..7.3.666...0j0i67k1j0i7i30k1j0i7i5i30k1j0i8i7i30k1.0.nz3OMQHvOIQ)
5. Lady Bug [(Lady Bug Google artwork)](https://www.google.com/search?q=ladybug+arcade+cabinet&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi37pbKvt_XAhVIZVAKHU4oDNAQ_AUIDCgD&biw=1322&bih=789#imgrc=yLZCCjTQJ2CYDM:)

It seems like Zaxxon has a lot of black bezels but [Mr. Do's Artwork Website](http://mrdo.mameworld.info/mame_artwork_ingame.php) has a pretty nice one as a few of the other games are in Mr. Do's repository of in-game artwork.

**Comment by UDb23** [comment]
Being real classics the games you list deserve an overlay ! Thanks for also adding the links for potential art; luckily I already collected high res artwork for most of these.
Only thing I cannot commit is timing to create/deliver these overlays.

**Comment by Wilstorm** [comment]
That's great! It's no hurry at all and I am truly grateful that you make them! Thanks UDb and have a great evening! ;)

**Comment by UDb23** [comment]
Congo Bongo [done](https://retropie.org.uk/forum/topic/15093/new-overlay-congo-bongo)

**Comment by Wilstorm** [comment]
It looks amazing! Your work is truly incredible and so clean and readable, nicely done! :)

**Comment by UDb23** [comment]
Zaxxon done.

**Comment by edwardsd97** [comment]
I have a reasonably decent Alien Syndrome overlay I put together with some parts from a 4x3 version someone made:
![aliensyn](https://user-images.githubusercontent.com/6161979/37595364-9025af6c-2b46-11e8-8b6f-05153bdabb5e.png)

**Comment by UDb23** [comment]
@edwardsd97 Well done, do you want to submit it to the Repo ?
It would require also corresponding info.txt and cfg files.

**Comment by edwardsd97** [comment]
Done

**Comment by UDb23** [comment]
Nice.
Modified info.txt: added _creator = "edwardsd97"_

**Comment by Wilstorm** [comment]
@edwardsd97 - Thank you for the overlay. This is a staple game in my library and I will be adding it today. 

Hey @UDb23 , do you still update that main thread when you add an overlay? I am using a good 50 or so overlays from the repository. Basically if I have the game installed I use the overlay. :)

**Comment by UDb23** [comment]
@Wilstorm 
>do you still update that main thread when you add an overlay? 

What do you mean with main thread ? On Retropie's forum there is no "main" thread, you can check for new overlays by searching for posts that start with "New overlay:".
Last one was Space Panic.

This Todo list here on Github actually is just a personal support for my own todo list, so does not necessarily includes every overlay I make (sometimes I decide at the last moment or change priorities).
Sorry for that.
Currently working on making Crazy balloon bezel and marquee (just recently found out no good quality complete marquee image exists and bezel has not been recreated at all so far)
